### ISSUE TITLE
feat: ✨ Add better types for custom events

### ISSUE THREAD

**Issue by schilchSICKAG** [synergy-design-system/synergy-design-system#281]
# Checklist (for the issue creator)

- [x] I have looked at the documentation site and was not able to find the required feature.
- [x] I have looked into the Figma boards and was not able to find the required feature.
- [ ] I would be willing to provide a PR for this feature.

# Story

As a [DEVELOPER] of the Synergy Design System, I would like to [have better types] so that [developers have better support for typescript when using our custom events].

## Current version:

```typescript
import type { SynInputEvent } from '@synergy-design-system/components`;

document.addEventListener('syn-input', (e: SynInputEvent) => {
  console.log(e.target); // Works, but has type of EventTarget
  console.log(e.target.value); // Does not work, as the type of e.target is not SynInput (e.g. the component);
});
```

## Current fix:

You are currently able to just cast `e.target` to the given element instance like this:

```typescript
import type { SynInput, SynInputEvent } from '@synergy-design-system/components`;

document.addEventListener('syn-input', (e: SynInputEvent) => {
  console.log(e.target); // Works, but has type of EventTarget
  console.log((e.target as SynInput).value); // Works, as we cast e.target as SynInput
});
```

## Wanted outcome

```typescript
import type { SynInputEvent } from '@synergy-design-system/components`;

document.addEventListener('syn-input', (e: SynInputEvent) => {
  console.log(e.target); // Works, has a type of SynInput now
  console.log(e.target.value); // Works, because the type is now SynInput
});
```

# Acceptance criteria

- [ ] All DoD items successfully completed
- [ ] The type support is implemented in the components, as well as all framework wrappers.

**Comment by kirchsuSICKAG** [comment]
We have taken a look at this improvement, but unfortunately it is not easy to implement. 
We can't implement it directly in our web components because we can only assign general event types in the GlobalEventHandlersEventMap. If we would assign an element type directly (see picture), every syn-blur event, even if it comes from the text field, would appear to have the type SynButton.

![Image](https://github.com/synergy-design-system/synergy-design-system/assets/115139104/f8aaa38c-0312-4a3a-9cc4-4355017a6e59)

Another possibility would be to add the specific types into the wrapper directly. In every component we could explicitly export the event with the set target like following: 

![Image](https://github.com/synergy-design-system/synergy-design-system/assets/115139104/8da09948-da1c-4302-91d7-83afa2f1ec63)

The problem with this solution is, that we will get a lot of new event types. We will get `m` (event type) x `n` (component type) new event type exports. 
If the user accidentally imports the wrong event type (e.g. he needs the event type for the button but imports it from the text field, because the event type name is the same), the target will have the wrong type.

For this reasons we will stop the investigation of this ticket. Maybe there is a good solution, but till now we haven`t found it.
