### ISSUE TITLE
fix: 🐛 Mark form as invalid when invalid (out of bounds) numeric value is provided

### ISSUE THREAD

**Issue by petanni** [synergy-design-system/synergy-design-system#596]
# Checklist (for the issue creator)

- [x] I have verified the bug exists in the latest version of `@synergy-design-system/components` (e.g. via `pnpm install @synergy-design-system/components`).
- [x] I can provide a simple, reproducible example of the issue (e.g. via code-sandbox or sample code, ...).
- [ ] I would be willing to provide a PR for this issue.

# Version

The bug occurred with the following version of the component library: `2.5.0`

# Component

The issue arises when using the following component(s): `syn-input`

# Environment

The issue occurred with the following operating system(s): `Windows 10`
The issue occurred in the following browser(s): `Google Chrome`

# Description

When using the `syn-input` component, with assigned `"number"` type, and also setting `[min]`, `[max]`, `[pattern]` attributes, the form that wraps this input does not get marked as "invalid".

**Context**: We are using Angular 18 so, according to that, we are using `ngForm`'s `ng-valid`/`ng-invalid` (or, in our script `form.valid` property) to control whether a (Next/Apply/Finish) button would be enabled or disabled.

Here is a snippet of how our code, that should achieve that, looks like:

HTML template:

``` html
<form #form="ngForm" [appForm]="form">
  <syn-input 
    type="number"
    [min]="0"
    [(ngModel)]="fenceTimeout"
    name="fenceTimeout">
  </syn-input>
</form>
```

Our custom directive which purpose is to just report (among some other stuff) on validity of the underlying form:

``` ts
@Directive({
  selector: '[appForm]',
  exportAs: 'form',
})
export class FormDirective implements AfterViewInit {
  appForm = input.required<NgForm>();
  isValid$ = new BehaviorSubject<boolean>(false);

  ngAfterViewInit(): void {
    this.isValid$.next(this.appForm().form.valid);
  }

  @HostListener('input')
  onInput(): void {
    this.isValid$.next(this.appForm().form.valid);
  }
}
```

# Acceptance criteria

- [ ] Having invalid values provided to numeric `syn-input`s with `[min]`, `[max]`, ... attributes in the form should be picked up by that form and mark it as invalid

**Comment by schilchSICKAG** [comment]
Hi @petanni,

unfortunately Angular has various modes that may (or may not) hold true for your scenario.

## 1. If you just want to use the built in validation:

Per default, Angular adds a `novalidate` attribute to all forms rendered by it. This is done to prevent clashes between [native html validation with angulars custom one](https://v17.angular.io/api/forms/NgForm#native-dom-validation-ui). Therefore, the validation normally taking place with our inputs is **disabled per default** (which is [exactly what `<form novalidate>` should do](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#novalidate)). To enable it, you can add a `ngNativeValidate` attribute to your form like so: `<form ngNativeValidate>`.

This will enable the regular HTML validation and will make required, min and max work.

## 2. Using it in template driven forms:

Just proceed as [described here](https://angular.dev/guide/forms/form-validation#validating-input-in-template-driven-forms). After assigning a value, you will be able to play with it. However, keep in mind that the `novalidate` statement from above still holds true: You will not be able to validate with a couple of properties :(


## 3. Using reactive forms:

When using a reactive form, you will have to [apply your wanted validators in the model](https://angular.dev/guide/forms/form-validation#validating-input-in-reactive-forms) as they are used as a single source of truth. In this case, you may omit the `min`, `max` and `required` attributes in the templates completely as the validation is completely driven by angular.

Hope this helps. Please get in touch with us if the problem is not solvable with one of the above steps.

**Comment by kirchsuSICKAG** [comment]
This is a valid request anyway. Tested it myself and there is something not exactly right with our <syn-input type="number"> in an angular form. Therefore we need to have a look at it

**Comment by kirchsuSICKAG** [comment]
Some form validations are not working correctly in angular:
 - `<syn-input type="number" />` with `min` attribute
 - `<syn-input type="number" />` with `max` attribute
 - `<syn-checkbox />` with `required` attribute

Angular automatically adds custom css classes to all form input elements and to the `<form />` element itself. For more information about this have a look at [the details of the angular css classes](https://v17.angular.io/guide/form-validation#control-status-css-classes).
The classes are added after the [angular built-in validator functions](https://v17.angular.io/api/forms/Validators) (like a required validator) are executed for the input element.

Some of the validator functions are working out of the box with our synergy input elements, because they are added automatically. This is because the selector, which decides if a validator is used, suits for them.

A working example is the required validator. It is used correctly for our components because the selector looks like following and therefore takes action:
```
 ':not([type=checkbox])[required][formControlName],:not([type=checkbox])[required][formControl],:not([type=checkbox])[required][ngModel]',
```

This is not the case for the ["min"](https://github.com/angular/angular/blob/e603e5616d2c3830a641d4cf76c891af0059798c/packages/forms/src/directives/validators.ts#L276), ["max"](https://github.com/angular/angular/blob/e603e5616d2c3830a641d4cf76c891af0059798c/packages/forms/src/directives/validators.ts#L224) and ["checkbox required"](https://github.com/angular/angular/blob/e603e5616d2c3830a641d4cf76c891af0059798c/packages/forms/src/directives/validators.ts#L429) validator. They are specific for an `<input />` element and therefore do not activate for our components:
```
 'input[type=number][min][formControlName],input[type=number][min][formControl],input[type=number][min][ngModel]',
```
