### ISSUE TITLE
fix: 🐛 changing active syn-tab / syn-panel via code is not working

### ISSUE THREAD

**Issue by kirchsuSICKAG** [synergy-design-system/synergy-design-system#604]
# Checklist (for the issue creator)

- [x] I have verified the bug exists in the latest version of `@synergy-design-system/components` (e.g. via `pnpm install @synergy-design-system/components`).
- [x] I can provide a simple, reproducible example of the issue (e.g. via code-sandbox or sample code, ...).
- [x] I would be willing to provide a PR for this issue.

# Version

The bug occurred with the following version of the component library: 2.7.0

# Component

The issue arises when using the following component(s): syn-tab, syn-panel, syn-tab-group

# Environment

The issue occurred with the following operating system(s): all
The issue occurred in the following browser(s): all

# Description
Changing the active tab via the "active" property in javascript does not work.
The old active tab and tab panels are not set "active=false" and even if setting the old active tab / panel "active=false" before leads to the old tab having the indicator and even showing both panels (the old active panel and the new active one).
see following codepen: https://codepen.io/kirchsuSICKAG/pen/xxoQXLE

# Acceptance criteria

- [ ] All DoD items successfully completed
- [ ] Either shoelace provides the fix
- [ ] Or we need to vendor the fix

**Comment by schilchSICKAG** [comment]
This does not seem to be a bug, but just rather annoing and unintuitive. The problem here is that a setter is used, e.g. `item.active = true;`. What happens is that in this case, the dom property `active` is added. However, it is also added when you provide `item.active = false`, as you can see in the DOM. The solution is using `setAttribute('active', false)` instead, as can be seen [on my pen](https://codepen.io/schilchSICKAG/pen/RwzvmNW) (just a copy of yours, using `setAttribute`). Maybe the property is not reflected properly?

**Comment by schilchSICKAG** [comment]
Also see [538](https://github.com/synergy-design-system/synergy-design-system/issues/538)

**Comment by kirchsuSICKAG** [comment]
I created a [bug issue](https://github.com/shoelace-style/shoelace/issues/2298) and provided a [PR] (https://github.com/shoelace-style/shoelace/pull/2299) in shoelace
